In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
data=pd.read_excel("Iris-train.xlsx")
data

     sepallength  sepalwidth  petallength  petalwidth           class
0            7.9         3.8          6.4         2.0  Iris-virginica
1            7.7         3.8          6.7         2.2  Iris-virginica
2            7.7         3.0          6.1         2.3  Iris-virginica
3            7.7         2.8          6.7         2.0  Iris-virginica
4            7.7         2.6          6.9         2.3  Iris-virginica
..           ...         ...          ...         ...             ...
111          4.5         2.3          1.3         0.3     Iris-setosa
112          4.4         3.2          1.3         0.2     Iris-setosa
113          4.4         3.0          1.3         0.2     Iris-setosa
114          4.4         2.9          1.4         0.2     Iris-setosa
115          4.3         3.0          1.1         0.1     Iris-setosa

[116 rows x 5 columns]

In [7]:
x_train=data.iloc[:,:-1]
y_train=data.iloc[:,-1]

In [8]:
x_train

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [9]:
y_train

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [10]:
model=RandomForestClassifier()

In [12]:
model.fit(x_train,y_train)
prediction1=model.predict([[5.4,3,4.5,1.5]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [13]:
prediction1

array(['Iris-versicolor'], dtype=object)

In [14]:
datatest=pd.read_excel("Iris-test.xlsx")
x_test=datatest.iloc[:,:-1]

prediction2=model.predict(x_test.values)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [15]:
prediction2

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)