In [19]:
import pandas as pd
df=pd.read_csv("data_cleaning_sample.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        delhi      M    charlie@example  20-07-2021

In [20]:
df["Age"].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
7    False
8     True
Name: Age, dtype: bool

In [21]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [22]:
df["Age"].fillna(df["Age"].mean())
#to implement this change assign it df["Age"]=*****

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [23]:
df.loc[1,"Age"]=df["Age"].mean()
#this can change a single element

In [24]:
df

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie        NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.000000        Delhi      F     eve@domain.com         NaN
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021
8  Charlie        NaN        delhi      M    charlie@example  20-07-2021

In [25]:

df.dropna()#Returns datafame containing row with no NaNs
#to assign : df=df.dropna()

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021

In [26]:
df.dropna(axis=1)#returns Dataframe having coulmn with no NaN

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        delhi      M    charlie@example

In [27]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8    False
dtype: bool

In [28]:
df.drop_duplicates()

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie        NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.000000        Delhi      F     eve@domain.com         NaN
8  Charlie        NaN        delhi      M    charlie@example  20-07-2021

In [29]:
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [30]:
df.drop_duplicates(subset=["Gender"])

      Name        Age      City Gender              Email   Join Date
0    Alice  25.000000  New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333     Delhi      M    charlie@example  20-07-2021

In [31]:
df

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie        NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.000000        Delhi      F     eve@domain.com         NaN
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021
8  Charlie        NaN        delhi      M    charlie@example  20-07-2021

In [32]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [33]:
df["City"].str.contains("delhi",case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [34]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [35]:
df2=df.dropna().copy()
df2["Age"]=df2["Age"].astype(int)

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      object
 1   Age        6 non-null      int64
 2   City       6 non-null      object
 3   Gender     6 non-null      object
 4   Email      6 non-null      object
 5   Join Date  6 non-null      object
dtypes: int64(1), object(5)
memory usage: 336.0+ bytes

In [38]:
df["Join Date"] = pd.to_datetime(df["Join Date"], dayfirst=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        7 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 564.0+ bytes

In [40]:
df["Age Group"]=df["Age"].apply(lambda x:"Adult" if x>21 else "Minor")

In [41]:
df

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25.000000,New York,F,alice@example.com,2021-05-01,Adult
1,Charlie,25.833333,Delhi,M,charlie@example,2021-07-20,Adult
2,Bob,30.000000,Los Angeles,M,bob@example.com,2020-06-15,Adult
3,Charlie,NaN,Delhi,M,charlie@example,2021-07-20,Minor
4,David,22.000000,Mumbai,M,david@example.com,2019-11-12,Adult
5,NaN,28.000000,Delhi,F,eve@domain.com,NaT,Adult
6,Alice,25.000000,New York,F,alice@example.com,2021-05-01,Adult
7,Alice,25.000000,New York,F,alice@example.com,2021-05-01,Adult
8,Charlie,NaN,delhi,M,charlie@example,2021-07-20,Minor

In [42]:
df["Gender"]=df["Gender"].map({"M":"Male","F":"Female"})

In [43]:
df

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25.000000,New York,Female,alice@example.com,2021-05-01,Adult
1,Charlie,25.833333,Delhi,Male,charlie@example,2021-07-20,Adult
2,Bob,30.000000,Los Angeles,Male,bob@example.com,2020-06-15,Adult
3,Charlie,NaN,Delhi,Male,charlie@example,2021-07-20,Minor
4,David,22.000000,Mumbai,Male,david@example.com,2019-11-12,Adult
5,NaN,28.000000,Delhi,Female,eve@domain.com,NaT,Adult
6,Alice,25.000000,New York,Female,alice@example.com,2021-05-01,Adult
7,Alice,25.000000,New York,Female,alice@example.com,2021-05-01,Adult
8,Charlie,NaN,delhi,Male,charlie@example,2021-07-20,Minor

In [44]:
df["City"]=df["City"].replace({"delhi":"Delhi","Mumbai":"Navi Mumbai"})

In [45]:
df

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25.000000,New York,Female,alice@example.com,2021-05-01,Adult
1,Charlie,25.833333,Delhi,Male,charlie@example,2021-07-20,Adult
2,Bob,30.000000,Los Angeles,Male,bob@example.com,2020-06-15,Adult
3,Charlie,NaN,Delhi,Male,charlie@example,2021-07-20,Minor
4,David,22.000000,Navi Mumbai,Male,david@example.com,2019-11-12,Adult
5,NaN,28.000000,Delhi,Female,eve@domain.com,NaT,Adult
6,Alice,25.000000,New York,Female,alice@example.com,2021-05-01,Adult
7,Alice,25.000000,New York,Female,alice@example.com,2021-05-01,Adult
8,Charlie,NaN,Delhi,Male,charlie@example,2021-07-20,Minor