In [24]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2], [3, 4]])
df1 = pd.DataFrame(arr,index=["A","B"],columns=["no1","no2"])
print(df1)

   no1  no2
A    1    2
B    3    4

In [18]:
df2=pd.read_excel("EXCELfile.xlsx")
print(df2)

     Name   Marks Results
0   Ashvin    100    Pass
1  Shubham     89    Pass
2    Virat     90    Pass
3  Anushka     98    Pass

In [19]:
df3=pd.read_csv("CSVfile.csv")
print(df3)

     Name   Marks Results
0   Ashvin    100    Pass
1  Shubham     89    Pass
2    Virat     90    Pass
3  Anushka     98    Pass

In [20]:
df4 = pd.read_csv("CSVfile.csv", usecols=["Results","Marks"]) #Also works for others like excel
print(df4)

   Marks Results
0    100    Pass
1     89    Pass
2     90    Pass
3     98    Pass

In [21]:
df1.index = ["a", "b", ]
df1.columns = ["Name", "Age"]

In [22]:
df1

   Name  Age
a     1    2
b     3    4

In [26]:
data=[[1,2,3],[0,0,9]]
df5=pd.DataFrame(data)
df5

   0  1  2
0  1  2  3
1  0  0  9

In [40]:
import json
df6=pd.read_json("Data.json")
df6

      user  pages
0  Ashwani     23
1   Shikha     24

In [32]:
#Using Url csv
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [41]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [42]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [44]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [45]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [46]:
df.shape

(244, 7)