In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [5]:
df2=df.melt(id_vars=["Name"],value_vars=["Math","Science","English"],var_name="Subject",value_name="Marks")
print(df2)

      Name  Subject  Marks
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [20]:
df3=df2.pivot(index="Name",columns="Subject",values="Marks")# cannot handle ssame row dtat with different value columns
print(df3)

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [22]:
df2.loc[9]={"Name":"Alice","Subject":"Math","Marks":90}
df2

      Name  Subject  Marks
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94
9    Alice     Math     90

In [25]:
df4=df2.pivot_table(index="Name",columns="Subject",values="Marks",aggfunc="mean")
df4

Subject  English  Math  Science
Name
Alice       88.0  87.5     90.0
Bob         85.0  78.0     82.0
Charlie     94.0  92.0     89.0