In [1]:
import pandas as pd
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [2]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [7]:
pd.merge(employees,departments,on="DeptID",)#inner join(how="inner") as default

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [8]:
pd.merge(employees,departments,on="DeptID",how="left")#left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [9]:
pd.merge(employees,departments,on="DeptID",how="right")#right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [10]:
pd.merge(employees,departments,on="DeptID",how="outer")#outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [16]:
df1=pd.DataFrame({
    "Name":["Ashwani","Shikha"],
    "Age":["20","21"]
})
df2=pd.DataFrame({
    "Name":["Mohit","Sharmila Siwach"],
    "Score":["19","21"]
})

In [18]:
pd.concat([df1,df2])

              Name  Age Score
0          Ashwani   20   NaN
1           Shikha   21   NaN
0            Mohit  NaN    19
1  Sharmila Siwach  NaN    21

In [19]:
pd.concat([df1,df2],axis=1)

      Name Age             Name Score
0  Ashwani  20            Mohit    19
1   Shikha  21  Sharmila Siwach    21