In [2]:
import pandas as pd
df=pd.read_csv("Data2.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df.head()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

In [4]:
df.tail()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 12 non-null     object
 1   Film                  12 non-null     object
 2   Year                  12 non-null     int64
 3   Genre                 12 non-null     object
 4   BoxOffice(INR Crore)  12 non-null     int64
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes

In [6]:
df.describe()

              Year  BoxOffice(INR Crore)       IMDb
count    12.000000             12.000000  12.000000
mean   2019.000000            545.666667   6.975000
std       2.215647            528.535942   0.981766
min    2016.000000            111.000000   5.600000
25%    2017.750000            249.750000   6.075000
50%    2018.500000            386.500000   7.000000
75%    2019.750000            570.000000   7.675000
max    2023.000000           2024.000000   8.400000

In [7]:
df.columns

Index(['Actor', 'Film', 'Year', 'Genre', 'BoxOffice(INR Crore)', 'IMDb'], dtype='object')

In [8]:
df.shape

(12, 6)

In [9]:
df.index=["A","B","C","D","E","F","G","H","I","J","K","L"]

In [11]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
A,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
B,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
C,Aamir Khan,Dangal,2016,Biography,2024,8.4
D,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
E,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
F,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
G,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
H,Hrithik Roshan,War,2019,Action,475,6.5
I,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
J,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
K,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
L,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [12]:
df["Actor"]

A        Shah Rukh Khan
B           Salman Khan
C            Aamir Khan
D         Ranbir Kapoor
E         Ranveer Singh
F    Ayushmann Khurrana
G         Rajkummar Rao
H        Hrithik Roshan
I          Akshay Kumar
J         Kartik Aaryan
K          Varun Dhawan
L         Vicky Kaushal
Name: Actor, dtype: object

In [13]:
type(df["Actor"])# this is a series not dataframe

pandas.core.series.Series

In [17]:
#for multiple columns
df[["Actor","IMDb"]]
type(df[["Actor","IMDb"]])# this returns a dataframe

pandas.core.frame.DataFrame

In [45]:
#for specific element 
df["Actor"]["A"] #if you have given label to a dataframe you have to use its label to access it row

'Shah Rukh Khan'

In [21]:
#row access using index
df.iloc[5]

Actor                   Ayushmann Khurrana
Film                             Andhadhun
Year                                  2018
Genre                             Thriller
BoxOffice(INR Crore)                   111
IMDb                                   8.3
Name: F, dtype: object

In [22]:
#row access using label 
df.loc["C"]

Actor                   Aamir Khan
Film                        Dangal
Year                          2016
Genre                    Biography
BoxOffice(INR Crore)          2024
IMDb                           8.4
Name: C, dtype: object

In [48]:
#specfic row and column
#using label
print(df.loc["A","Actor"])
#using index
print(df.iloc[0,0])
#you can also use slicing in it too
print(df.loc["A":"C",["Actor","Film"]])#this will include the Stoping point like:"C"
print(df.iloc[0:2,0:4])

<class 'str'>
Shah Rukh Khan
            Actor             Film
A  Shah Rukh Khan          Pathaan
B     Salman Khan  Tiger Zinda Hai
C      Aamir Khan           Dangal
            Actor             Film  Year   Genre
A  Shah Rukh Khan          Pathaan  2023  Action
B     Salman Khan  Tiger Zinda Hai  2017  Action

In [47]:
#filtering in pandas is fancy indexing
df[(df["IMDb"]>8) & (df["Year"]>2018)]

pandas.core.frame.DataFrame

In [67]:
# for faser access of single element we use ".at" and ".iat"
print(df.at["A","Year"])
print(df.iat[0,1])

2023
Pathaan

In [72]:
# if series and dataframe are returned using above function then it is a view
# but if a element like string, float , int is returned is a copy 
# to copy the dataframe and series we use df.query("<Sql_like language>")
# in case you find space between column name use :column name`
# do not use name of module
# and , or , not instead &,|,~
#case sensitive
#pandas doesnot gurantee a view and copy . waht it is but .query gurantees copy 
#Or you can use .copy()
var=7
df.query("Year != 2019 and IMDb > @var")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
A,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
C,Aamir Khan,Dangal,2016,Biography,2024,8.4
F,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
G,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5

In [78]:
df.query("2019<Year<=2022")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
D,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
J,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9