In [2]:
import pandas as pd
df=pd.read_csv("Data2.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df.sort_values(["Year","BoxOffice(INR Crore)"])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
7,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [6]:
df2=df.sort_values("Year",ascending=False)
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [7]:
df2.iloc[2,0]

'Kartik Aaryan'

In [8]:
df2.loc[2,"Actor"]

'Aamir Khan'

In [9]:
df2.reset_index(drop=True)#these change won't apply to real one

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
2,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Hrithik Roshan,War,2019,Action,475,6.5
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
7,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [10]:
df2.sort_index()#use inplace =True for change in real one

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [11]:
df2.reset_index(drop=True,inplace=True)#inplace to chnage in real one 
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
2,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Hrithik Roshan,War,2019,Action,475,6.5
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
7,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [12]:
df2["Rank"]=df2["IMDb"].rank(ascending=False,method="dense")#method="dense" will return integer values ranking as default it is float
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
2,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
3,Hrithik Roshan,War,2019,Action,475,6.5,7.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
6,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
7,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [13]:
df2.sort_values("Rank",inplace=True)

In [14]:
df2.reset_index(drop=True,inplace=True)
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
2,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
4,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
5,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
6,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
11,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0

In [15]:
df2.rename(columns={"Film":"Movie"},inplace=True)

In [16]:
df2.rename(index={11:12},inplace=True)

In [17]:
df2

,Actor,Movie,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
2,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
4,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
5,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
6,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
12,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0

In [18]:
df2.index=["A","B","C","D","E","F","G","H","I","J","K","L"]

In [19]:
df2

,Actor,Movie,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
A,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
B,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
C,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
D,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
E,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
F,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
G,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
H,Hrithik Roshan,War,2019,Action,475,6.5,7.0
I,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
J,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
K,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
L,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0

In [20]:
cols=["Movie"]+[c for c in df2.columns if c!="Movie"]
df2=df2[cols]#this take Movie in front

In [21]:
df2

,Movie,Actor,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
A,Dangal,Aamir Khan,2016,Biography,2024,8.4,1.0
B,Andhadhun,Ayushmann Khurrana,2018,Thriller,111,8.3,2.0
C,Uri: The Surgical Strike,Vicky Kaushal,2019,Action,342,8.2,3.0
D,Stree,Rajkummar Rao,2018,Horror Comedy,180,7.5,4.0
E,Pathaan,Shah Rukh Khan,2023,Action,1050,7.2,5.0
F,Good Newwz,Akshay Kumar,2019,Comedy,318,7.0,6.0
G,Padmaavat,Ranveer Singh,2018,Historical,585,7.0,6.0
H,War,Hrithik Roshan,2019,Action,475,6.5,7.0
I,Badrinath Ki Dulhania,Varun Dhawan,2017,Romantic Comedy,201,6.1,8.0
J,Tiger Zinda Hai,Salman Khan,2017,Action,565,6.0,9.0
K,Bhool Bhulaiyaa 2,Kartik Aaryan,2022,Horror Comedy,266,5.9,10.0
L,Brahmastra,Ranbir Kapoor,2022,Fantasy,431,5.6,11.0