In [2]:
import pandas as pd
df=pd.read_csv("Data2.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df=df[df["Year"]>2018]

In [6]:
df.to_csv("UpdatedData.csv")#with index column

In [8]:
df.to_csv("UpdatedData2.csv",index=False)#without indexing column

In [12]:
df.to_excel("Excelfile.xlsx",index=False)

In [13]:
df1=pd.read_excel("Excelfile.xlsx",sheet_name="Sheet1")
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
2,Hrithik Roshan,War,2019,Action,475,6.5
3,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
4,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
5,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
with pd.ExcelWriter("Excelfile.xlsx") as file:
    df1.to_excel(file,sheet_name="Data1",index=False)

In [22]:
df2=pd.read_json("Data.json")

In [23]:
df2

      user  pages                                            address
0  Ashwani     23      {'City': 'Charkhi Dadri', 'Village': 'Mauri'}
1   Shikha     24  {'City': 'Charkhi Dadri', 'Village': 'Bageshwa...

In [27]:
data=[{
        "user": "Ashwani",
        "pages": 23,
        "address":{"City":"Charkhi Dadri","Village":"Mauri"}
    },
    {
        "user":"Shikha",
        "pages": 24,
        "address":{"City":"Charkhi Dadri","Village":"Bageshwari"}
    }]
df3=pd.json_normalize(data)

In [28]:
df3

      user  pages   address.City address.Village
0  Ashwani     23  Charkhi Dadri           Mauri
1   Shikha     24  Charkhi Dadri      Bageshwari